version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
      - PRISONER_SERVICE_URL=http://prisoner-service:5000
      - TURING_SERVICE_URL=http://turing-service:5001

  prisoner-service:
    build: ./prisoner-service
    ports:
      - "5000:5000"

  turing-service:
    build: ./turing-service
    ports:
      - "5001:5001"