version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    environment:
      PRISONER_SERVICE_URL: http://localhost:5000
      TURING_SERVICE_URL: http://localhost:5001
      DIGITIZER_SERVICE_URL: http://localhost:5002
      PLATERECOGNIZER_SERVICE_URL: http://localhost:5003
      PLATERECOGNIZER_API_TOKEN: your_token_here
      DATABASE_URL: postgresql://root:password@db/SmartParking
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: SmartParking
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"