name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/personalsite:latest .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/personalsite:latest
