name: Build and Push Web Docker Image

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/web:latest ./web

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/web:latest